/*
INPUT:
	MIN_TRUST_SCORE (TỪ HỆ THỐNG)
OUTPUT:
	DRIVER_ID, STATUS, TRUST_SCORE, DISTANCE_KM
LOGIC (IF/ELSE Ở TẦNG BACKEND):
	NẾU MIN_TRUST_SCORE LÀ NULL ==> GÁN MẶC ĐỊNH = 80
	NẾU MIN_TRUST_SCORE < 0 ==> LỖI ==> GÁN LẠI = 0 HOẶC = 80
	NẾU MIN_TRUST_SCORE > 100 ==> LỖI GÁN LẠI = 100 VÌ MAX = 100
BẪY DỮ LIỆU:
	NẾU MIN_TRUST_SCORE = -10 MÀ KHÔNG KIỂM TRA THÌ ĐIỀU KIỆN SQL TRUST_SCORE >= -10 SẼ LUÔN ĐÚNG VỚI HẦU HẾT TÀI XẾ KỂ CẢ TÀI XẾ KÉM
*/

SELECT * FROM DRIVERS
WHERE STATUS = 'AVAILABLE' AND TRUST_SCORE >= 80
ORDER BY 
DISTANCE_KM ASC,
TRUST_SCORE DESC;    

